IMAGE_NAME = "ubuntu/bionic64"
N = 3

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vbguest.auto_update = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
      
    (1..N).each do |machine_id|
        config.vm.define "node-#{machine_id}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.60.#{machine_id + 10}"
            node.vm.hostname = "node-#{machine_id}"
            node.vm.provision 'shell', path: 'scripts/setup-pki.sh'
            if machine_id == N
                node.vm.provision "ansible" do |ansible|
                    # ansible.verbose = "vvv"
                    ansible.limit = "all"
                    ansible.playbook = "kubernetes-setup/node-playbook.yml"
                end
            end
            # node.vm.provision "shell", inline: <<-SHELL
            #     cat /home/vagrant/.ssh/id_rsa.pub >> vagrant plugin install vagrant-vbguest
            # SHELL
            # end
        end
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.60.10"
        master.vm.hostname = "k8s-master"
        master.vm.provision 'shell', path: 'scripts/setup-pki.sh'
        master.vm.provision "ansible" do |ansible|
            # ansible.verbose = "v"
            ansible.playbook = "kubernetes-setup/master-playbook.yml"        
        end
    end

end 