
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "10.10.10.100"
  #config.vm.network "public_network"
  config.vm.synced_folder "data", "/vagrant_data"
  config.vm.network "forwarded_port", guest_ip: '10.20.20.1', guest: 80, host: 8080
  config.disksize.size = '50GB'

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "10240"
  end

  config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
    apt-get update
    apt-get install -y curl openssh-server ca-certificates
    snap install microstack --classic --edge
    sudo microstack.init --auto
  SHELL
end
