
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "10.0.10.100"
  #config.vm.network "public_network"
  config.vm.synced_folder "data", "/vagrant_data"
  config.vm.network "forwarded_port", guest_ip: '10.20.20.1', guest: 80, host: 8080
  config.disksize.size = '100GB'

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "12288"
  end

  config.vm.provision "shell", inline: <<-SHELL
    cd /tmp
    git clone https://opendev.org/openstack/devstack -b stable/stein
    cd devstack/
    cp /vagrant_data/local.conf local.conf
    chown vagrant /tmp/devstack/*
    chown vagrant /tmp/devstack
  SHELL
end
