---
- hosts: all
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Install docker and its dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      notify:
        - docker status

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        group: docker

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubectl

    - name: Install RKE binaries
      get_url:
        url: https://github.com/rancher/rke/releases/download/v0.3.2/rke_linux-amd64
        dest: /usr/local/bin/rke
        mode: "0761"

    # - name: Ensures /var/rke dir exists
    #   file:
    #     path: /var/rke
    #     state: directory
    #     mode: "0777"

    - name: Copy RKE config file
      copy:
        src: ./cluster.yml
        dest: /home/vagrant/cluster.yml

    - name: Initialize the Kubernetes cluster using RKE
      command: rke up
      args:
        chdir: /home/vagrant/
      register: init_output
      sudo: no

    - name: Setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /home/vagrant/kube_config_cluster.yml /home/vagrant/.kube/config
        - chown vagrant:vagrant /home/vagrant/.kube/config

    - name: Copy kubeconfig to local file
      sudo: no
      fetch:
        src: /home/vagrant/.kube/config
        dest: ./kube.config
        flat: yes

  handlers:
    - name: docker status
      service: name=docker state=started
