---
- hosts: all
  become: true
  vars:
    splunk_url: "https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.0.0&product=splunk&filename=splunk-8.0.0-1357bef0a7f6-linux-2.6-x86_64.rpm&wget=true"
    splunk_admin_password: p@ssword1
  tasks:
    - name: Download Splunk
      get_url:
        url: "{{ splunk_url }}"
        dest: /opt/splunk/splunk-linux-2.6-x86_64.rpm

    - name: Install Splunk
      yum:
        name: /opt/splunk/splunk-linux-2.6-x86_64.rpm
        state: present

    - name: Accept License
      command: "./splunk start --accept-license --no-prompt --answer-yes --seed-passwd {{ splunk_admin_password }}"
      args:
        chdir: /opt/splunk/bin

    - name: Start Splunk
      command: ./splunk enable boot-start
      args:
        chdir: /opt/splunk/bin
